// program where the user has to guess a number generated by a program

function guessNumber() {

    // generating a random integer from 1 to 10
    const random = Math.floor(Math.random() * 10) + 1;
//Math.floor () function rounds down a number to the next smallest integer

    // take input from the user
    let number = parseInt(prompt('Guess a number from 1 to 10: '));

    // take the input until the guess is correct
    while(number !== random) {
      
        alert('Not Matched');
        number = parseInt(prompt('Guess a number from 1 to 10: '));
    
    }


    
    if(number == random) {
        alert('Good Work.');
    }
   

  
}

guessNumber();